#!/usr/bin/env python3
"""Generate a structured Markdown review from a GitHub pull request diff."""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass


PR_RE = re.compile(r"^https://github\.com/([^/]+)/([^/]+)/pull/(\d+)/?$")


@dataclass
class DiffStats:
    files: int
    added: int
    removed: int
    tests_changed: bool
    docs_changed: bool
    risky_files: list[str]
    large_files: list[str]


def diff_url(pr_url: str) -> str:
    match = PR_RE.match(pr_url)
    if not match:
        raise SystemExit("error: --pr must be a GitHub pull request URL")
    owner, repo, number = match.groups()
    return f"https://github.com/{owner}/{repo}/pull/{number}.diff"


def fetch_diff(pr_url: str) -> str:
    request = urllib.request.Request(diff_url(pr_url), headers={"User-Agent": "claude-review"})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.read().decode("utf-8", errors="replace")
    except urllib.error.URLError as exc:
        raise SystemExit(f"error: could not fetch PR diff: {exc}") from exc


def analyze(diff: str) -> DiffStats:
    files = []
    added = 0
    removed = 0
    current_file = ""
    per_file_changes: dict[str, int] = {}

    for line in diff.splitlines():
        if line.startswith("diff --git "):
            parts = line.split(" b/", 1)
            current_file = parts[1] if len(parts) == 2 else line
            files.append(current_file)
            per_file_changes.setdefault(current_file, 0)
            continue
        if line.startswith("+") and not line.startswith("+++"):
            added += 1
            if current_file:
                per_file_changes[current_file] += 1
        elif line.startswith("-") and not line.startswith("---"):
            removed += 1
            if current_file:
                per_file_changes[current_file] += 1

    risky_markers = (
        "auth",
        "billing",
        "payment",
        "migration",
        "schema",
        "security",
        "permission",
        "token",
        "secret",
    )
    risky_files = [path for path in files if any(marker in path.lower() for marker in risky_markers)]
    large_files = [path for path, count in per_file_changes.items() if count >= 120]
    tests_changed = any("/test" in path.lower() or path.lower().endswith((".test.ts", ".test.py", ".spec.ts")) for path in files)
    docs_changed = any(path.lower().endswith((".md", ".mdx", ".rst")) for path in files)

    return DiffStats(
        files=len(files),
        added=added,
        removed=removed,
        tests_changed=tests_changed,
        docs_changed=docs_changed,
        risky_files=risky_files,
        large_files=large_files,
    )


def confidence(stats: DiffStats) -> str:
    if stats.risky_files or stats.large_files or stats.files > 12:
        return "Low"
    if stats.tests_changed or stats.docs_changed or stats.files <= 4:
        return "High"
    return "Medium"


def render(pr_url: str, stats: DiffStats) -> str:
    risks = []
    if stats.risky_files:
        risks.append("Touches sensitive areas: " + ", ".join(stats.risky_files[:5]))
    if stats.large_files:
        risks.append("Large per-file diff may hide regressions: " + ", ".join(stats.large_files[:5]))
    if not stats.tests_changed and not stats.docs_changed:
        risks.append("No tests or docs were changed, so behavior may need manual verification.")
    if not risks:
        risks.append("No obvious structural risk detected from the diff shape.")

    suggestions = []
    if not stats.tests_changed and not stats.docs_changed:
        suggestions.append("Add or reference targeted validation for the changed behavior.")
    if stats.risky_files:
        suggestions.append("Ask for extra maintainer review on auth, billing, schema, or secret-handling paths.")
    if stats.large_files:
        suggestions.append("Split large files or explain why the broad change is necessary.")
    if not suggestions:
        suggestions.append("Keep the PR focused and include the validation command in the PR body.")

    return f"""## Summary

This PR changes {stats.files} file(s), with {stats.added} additions and {stats.removed} deletions. The diff appears {'documentation-oriented' if stats.docs_changed else 'code-oriented'}, and {'includes test changes' if stats.tests_changed else 'does not include test changes'}.

## Identified Risks

{chr(10).join(f"- {risk}" for risk in risks)}

## Improvement Suggestions

{chr(10).join(f"- {suggestion}" for suggestion in suggestions)}

## Confidence

{confidence(stats)}

<!-- Generated by claude_review.py for {pr_url} -->
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Review a GitHub pull request diff.")
    parser.add_argument("--pr", required=True, help="GitHub pull request URL")
    args = parser.parse_args()

    diff = fetch_diff(args.pr)
    if not diff.strip():
        raise SystemExit("error: PR diff is empty or unavailable")
    print(render(args.pr, analyze(diff)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
